In [1]:
import wave, struct, os, glob, librosa, pickle
import numpy as np

In [2]:
with open ('data', 'rb') as fp:
    data = pickle.load(fp)

In [3]:
with open ('label', 'rb') as fp:
    label = pickle.load(fp)

In [4]:
len(data)

44242

In [5]:
mx = []
for i in range(len(data)):
    mx.append(data[i].shape[1])

In [6]:
u,c = np.unique(mx, return_counts = True)

In [7]:
u

array([ 26,  37,  40,  47,  53,  54,  56,  58,  59,  60,  61,  62,  63,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  91,  92,
        93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104, 105,
       106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118,
       119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131,
       132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144,
       145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157,
       158, 159, 160, 161, 162, 164, 165, 166, 167, 168, 169, 170, 171,
       172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184,
       186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198,
       199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 210, 211, 212,
       214, 215, 216, 217, 218, 219, 220, 221, 223, 225, 227, 228, 229,
       230, 232, 234, 235, 236, 238, 239, 240, 241, 243, 245, 24

In [8]:
c

array([  1,   2,   1,   1,   1,   1,   1,   8,   3,   2,  14,   1,  22,
        24,   1,  36,   2,  40,  46,  16,  93,   1, 101,   1, 148, 145,
         2, 154, 126,  63, 226,   3, 267,   2, 289,   4, 342, 319, 203,
       185, 435,   5, 456,   3, 477,   8, 557,   1, 554, 262, 373, 639,
         4, 650,   5, 704,   3, 687,   1, 733, 214, 545, 761,   8, 778,
         4, 810,   3, 761,   6, 805, 155, 714, 715,  76, 838,   4, 805,
         3, 776,   4, 805,  45, 750, 552, 167, 729,   2, 741,   1, 731,
         2, 726,   2, 721, 473, 213, 700,   3, 662,   1, 608,   6, 646,
         2, 603, 317, 261, 542, 589,   2, 521,   3, 503,   2, 474, 232,
       275, 473,   1, 483,   3, 471,   1, 469,   2, 419, 134, 247, 365,
       334,   1, 350,   2, 329,   1, 329,  76, 234, 300,  14, 278,   2,
       296,   1, 271,   2, 274,  26, 214, 206,  40, 227, 220,   2, 191,
       189,   2, 178, 153,  47, 158,   1, 181, 139, 130, 136,  81,  50,
       140, 132, 113,   1, 118,  96,  47,  49, 110,  78,  92,  7

In [9]:
data[0].shape

(20, 89)

In [10]:
data_now = []
label_now = []
for i in range(len(data)):
    l = data[i].shape[1]
    if l <= 339:
        l = 339 - l
        lft = int(l/2)
        rgt = l - lft
        dat = np.pad(data[i][:15],[[0,0],[lft,rgt]], mode = 'wrap')
        data_now.append(dat.flatten())
        label_now.append(label[i])

In [11]:
data_now[0].shape

(5085,)

In [12]:
len(data_now)

43584

In [13]:
len(label_now)

43584

In [14]:
with open('data_2_15_mfcc', 'wb') as fp:
    pickle.dump(data_now, fp)

In [15]:
with open('label_2_15_mfcc', 'wb') as fp:
    pickle.dump(label_now, fp)

In [16]:
u,c = np.unique(label_now, return_counts = True)

In [17]:
u

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108])

In [18]:
c

array([223, 344, 379, 358, 376, 390, 455, 409, 368, 355, 490, 333, 443,
       501, 374, 350, 386, 418, 345, 349, 472, 365, 331, 479, 360, 374,
       372, 393, 375, 293, 433, 410, 477, 354, 472, 388, 469, 477, 336,
       420, 415, 398, 394, 456, 445, 407, 429, 460, 415, 458, 456, 399,
       403, 408, 450, 363, 466, 422, 401, 465, 421, 408, 409, 378, 413,
       411, 408, 401, 402, 390, 397, 307, 340, 416, 418, 335, 406, 418,
       408, 420, 413, 410, 420, 171, 413, 419, 416, 416, 392, 416, 415,
       419, 420, 410, 411, 420, 422, 399, 383, 392, 415, 421, 421, 421,
       417, 417, 291, 417, 275], dtype=int64)